export const desginToken = {
  meta: {
    name: 'Corporate KPI Framework',
    style: 'Corporate Modern',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  colors: {
    surface: '#faf8ff',
    surfaceDim: '#d9d9e4',
    surfaceBright: '#faf8ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f3fd',
    surfaceContainer: '#ededf8',
    surfaceContainerHigh: '#e7e7f2',
    surfaceContainerHighest: '#e1e2ec',
    onSurface: '#191b23',
    onSurfaceVariant: '#434654',
    inverseSurface: '#2e3038',
    inverseOnSurface: '#f0f0fb',
    outline: '#737685',
    outlineVariant: '#c3c6d6',
    surfaceTint: '#0c56d0',
    primary: '#003d9b',
    onPrimary: '#ffffff',
    primaryContainer: '#0052cc',
    onPrimaryContainer: '#c4d2ff',
    inversePrimary: '#b2c5ff',
    secondary: '#006c47',
    onSecondary: '#ffffff',
    secondaryContainer: '#82f9be',
    onSecondaryContainer: '#00734c',
    tertiary: '#5e3c00',
    onTertiary: '#ffffff',
    tertiaryContainer: '#7d5200',
    onTertiaryContainer: '#ffca81',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#dae2ff',
    primaryFixedDim: '#b2c5ff',
    onPrimaryFixed: '#001848',
    onPrimaryFixedVariant: '#0040a2',
    secondaryFixed: '#82f9be',
    secondaryFixedDim: '#65dca4',
    onSecondaryFixed: '#002113',
    onSecondaryFixedVariant: '#005235',
    tertiaryFixed: '#ffddb3',
    tertiaryFixedDim: '#ffb950',
    onTertiaryFixed: '#291800',
    onTertiaryFixedVariant: '#624000',
    background: '#faf8ff',
    onBackground: '#191b23',
    surfaceVariant: '#e1e2ec',
  },
  semantic: {
    success: {
      main: '#006c47',
      contrastText: '#ffffff',
      container: '#82f9be',
      onContainer: '#00734c',
    },
    warning: {
      main: '#7d5200',
      contrastText: '#ffffff',
      container: '#ffddb3',
      onContainer: '#624000',
    },
    danger: {
      main: '#ba1a1a',
      contrastText: '#ffffff',
      container: '#ffdad6',
      onContainer: '#93000a',
    },
    info: {
      main: '#0052cc',
      contrastText: '#ffffff',
      container: '#dae2ff',
      onContainer: '#0040a2',
    },
  },
  typography: {
    displayKpi: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: '36px',
      fontWeight: 700,
      lineHeight: '44px',
      letterSpacing: '-0.02em',
    },
    h1: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: '24px',
      fontWeight: 600,
      lineHeight: '32px',
    },
    h2: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: '20px',
      fontWeight: 600,
      lineHeight: '28px',
    },
    bodyBase: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '20px',
    },
    bodySm: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: '12px',
      fontWeight: 400,
      lineHeight: '16px',
    },
    labelCaps: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: '11px',
      fontWeight: 700,
      lineHeight: '16px',
      textTransform: 'uppercase' as const,
    },
  },
  radius: {
    sm: '0.125rem',
    base: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
    input: '4px',
    button: '4px',
    card: '8px',
    chip: '9999px',
  },
  spacing: {
    base: '4px',
    xs: '8px',
    sm: '12px',
    md: '16px',
    lg: '24px',
    xl: '32px',
  },
  layout: {
    gridColumns: 12,
    gridGutter: '24px',
    sidebarWidth: '260px',
    cardPadding: '24px',
    baseline: '4px',
  },
  borders: {
    subtle: '1px solid #dfe1e6',
    input: '1px solid #c3c6d6',
    focus: '1px solid #0052cc',
  },
  elevation: {
    level0: {
      background: '#f4f5f7',
      border: 'none',
      boxShadow: 'none',
    },
    level1: {
      background: '#ffffff',
      border: '1px solid #dfe1e6',
      boxShadow: 'none',
    },
    level2: {
      background: '#ffffff',
      border: '1px solid #dfe1e6',
      boxShadow: '0 4px 8px rgba(25, 27, 35, 0.04)',
    },
  },
  components: {
    button: {
      primary: {
        background: '#0052cc',
        color: '#ffffff',
        hoverBackground: '#003d9b',
      },
      secondary: {
        background: 'transparent',
        color: '#434654',
        border: '1px solid #c3c6d6',
        hoverBackground: '#f3f3fd',
      },
    },
    input: {
      background: '#ffffff',
      text: '#191b23',
      placeholder: '#737685',
      border: '1px solid #c3c6d6',
      focusBorder: '1px solid #0052cc',
      errorBorder: '1px solid #7d5200',
    },
    card: {
      background: '#ffffff',
      border: '1px solid #dfe1e6',
      borderRadius: '8px',
      padding: '24px',
    },
    sidebar: {
      width: '260px',
      background: '#ffffff',
      activeIndicator: '#0052cc',
      activeBackground: '#f3f3fd',
      text: '#434654',
    },
    statusChip: {
      onTrack: {
        background: '#82f9be',
        color: '#00734c',
      },
      behind: {
        background: '#ffddb3',
        color: '#624000',
      },
    },
  },
} as const;

export type DesginToken = typeof desginToken;

export default desginToken;
